# Generated by Django 4.2.6 on 2023-12-14 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description_de',
            field=models.TextField(max_length=30000, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.TextField(max_length=30000, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_de',
            field=models.CharField(max_length=120, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(max_length=120, null=True, verbose_name='name'),
        ),
    ]
